### PR TITLE
Created documentation.xml

### PR DESCRIPTION
**Pull request by shreyans2007**

### CODE REVIEW

**Comment by jc00ke** [comment]
Hi! Can you elaborate on why we would need this file?

I received what feels like a similar PR on the MagLev site and I'm guessing it's a new form of spam.

**Comment by leocassarani** [comment]
@jc00ke I suspect it's related to this phenomenon (which I only learned about today): https://blog.domenic.me/hacktoberfest/

**Comment by jc00ke** [comment]
@leocassarani I bet you're right. That's really unfortunate.

**Comment by brixen** [comment]
Thank you @jc00ke and @leocassarani for handling this. ❤️

**Pull request closed without merging**
